import React from "react";

const Helo = () => {
  return (
    <div>
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t5f/1.5/30/1f600.png"
        alt="😀"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/te2/1.5/30/1f603.png"
        alt="😃"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t63/1.5/30/1f604.png"
        alt="😄"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/te0/1.5/30/1f601.png"
        alt="😁"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t65/1.5/30/1f606.png"
        alt="😆"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t4/1.5/30/1f979.png"
        alt="🥹"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/te4/1.5/30/1f605.png"
        alt="😅"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t61/1.5/30/1f602.png"
        alt="😂"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/te3/1.5/30/1f923.png"
        alt="🤣"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t7d/1.5/30/1f972.png"
        alt="🥲"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t4a/1.5/30/263a.png"
        alt="☺️"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t10/1.5/30/1f60a.png"
        alt="😊"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/te6/1.5/30/1f607.png"
        alt="😇"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/tdd/1.5/30/1f642.png"
        alt="🙂"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t5e/1.5/30/1f643.png"
        alt="🙃"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/te8/1.5/30/1f609.png"
        alt="😉"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t12/1.5/30/1f60c.png"
        alt="😌"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t93/1.5/30/1f60d.png"
        alt="😍"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t7b/1.5/30/1f970.png"
        alt="🥰"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t6/1.5/30/1f618.png"
        alt="😘"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t85/1.5/30/1f617.png"
        alt="😗"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t87/1.5/30/1f619.png"
        alt="😙"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/taf/1.5/30/1f61a.png"
        alt="😚"
      />
      <img
        src="https://static.xx.fbcdn.net/images/emoji.php/v9/t91/1.5/30/1f60b.png"
        alt="😋"
      />
    </div>
  );
};

export default Helo;
